docker buildx build --platform linux/amd64,linux/arm64 --push -t lskjs/clickhouse-client:latest dockerfiles/lskjs_clickhouse-client_latest && \
docker buildx build --platform linux/amd64,linux/arm64 --push -t lskjs/dind:latest dockerfiles/lskjs_dind_latest && \
docker buildx build --platform linux/amd64,linux/arm64 --push -t lskjs/kubectl:1.27 dockerfiles/lskjs_kubectl_1.27 && \
docker buildx build --platform linux/amd64,linux/arm64 --push -t lskjs/kubectl:1.30 dockerfiles/lskjs_kubectl_1.30 && \
docker buildx build --platform linux/amd64,linux/arm64 --push -t lskjs/kubectl:latest dockerfiles/lskjs_kubectl_latest && \
docker buildx build --platform linux/amd64,linux/arm64 --push -t lskjs/node:17.4.0 dockerfiles/lskjs_node_17.4.0 && \
docker buildx build --platform linux/amd64,linux/arm64 --push -t lskjs/node:17.4.0-alpine dockerfiles/lskjs_node_17.4.0-alpine && \
docker buildx build --platform linux/amd64,linux/arm64 --push -t lskjs/node:17.4.0-clickhouse-20.8.2.3 dockerfiles/lskjs_node_17.4.0-clickhouse-20.8.2.3 && \
docker buildx build --platform linux/amd64,linux/arm64 --push -t lskjs/node:18.10.0 dockerfiles/lskjs_node_18.10.0 && \
docker buildx build --platform linux/amd64,linux/arm64 --push -t lskjs/node:18.10.0-alpine dockerfiles/lskjs_node_18.10.0-alpine && \
docker buildx build --platform linux/amd64,linux/arm64 --push -t lskjs/node:18.10.0-puppeteer dockerfiles/lskjs_node_18.10.0-puppeteer && \
docker buildx build --platform linux/amd64,linux/arm64 --push -t lskjs/node:19.3.0 dockerfiles/lskjs_node_19.3.0 && \
docker buildx build --platform linux/amd64,linux/arm64 --push -t lskjs/node:19.3.0-alpine dockerfiles/lskjs_node_19.3.0-alpine && \
docker buildx build --platform linux/amd64,linux/arm64 --push -t lskjs/node:19.3.0-puppeteer dockerfiles/lskjs_node_19.3.0-puppeteer && \
docker buildx build --platform linux/amd64,linux/arm64 --push -t lskjs/node:19.5.0 dockerfiles/lskjs_node_19.5.0 && \
docker buildx build --platform linux/amd64,linux/arm64 --push -t lskjs/node:19.5.0-alpine dockerfiles/lskjs_node_19.5.0-alpine && \
docker buildx build --platform linux/amd64,linux/arm64 --push -t lskjs/node:19.5.0-clickhouse dockerfiles/lskjs_node_19.5.0-clickhouse && \
docker buildx build --platform linux/amd64,linux/arm64 --push -t lskjs/node:19.5.0-clickhouse-20.8.2.3 dockerfiles/lskjs_node_19.5.0-clickhouse-20.8.2.3 && \
docker buildx build --platform linux/amd64,linux/arm64 --push -t lskjs/node:19.5.0-puppeteer dockerfiles/lskjs_node_19.5.0-puppeteer && \
docker buildx build --platform linux/amd64,linux/arm64 --push -t lskjs/node:20.2.0 dockerfiles/lskjs_node_20.2.0 && \
docker buildx build --platform linux/amd64,linux/arm64 --push -t lskjs/node:20.2.0-alpine dockerfiles/lskjs_node_20.2.0-alpine && \
docker buildx build --platform linux/amd64,linux/arm64 --push -t lskjs/node:20.2.0-alpine-gyp dockerfiles/lskjs_node_20.2.0-alpine-gyp && \
docker buildx build --platform linux/amd64,linux/arm64 --push -t lskjs/node:20.2.0-clickhouse dockerfiles/lskjs_node_20.2.0-clickhouse && \
docker buildx build --platform linux/amd64,linux/arm64 --push -t lskjs/node:20.2.0-gyp dockerfiles/lskjs_node_20.2.0-gyp && \
docker buildx build --platform linux/amd64,linux/arm64 --push -t lskjs/node:20.2.0-playwright dockerfiles/lskjs_node_20.2.0-playwright && \
docker buildx build --platform linux/amd64,linux/arm64 --push -t lskjs/node:20.2.0-puppeteer dockerfiles/lskjs_node_20.2.0-puppeteer && \
docker buildx build --platform linux/amd64,linux/arm64 --push -t lskjs/node:21.6.0 dockerfiles/lskjs_node_21.6.0 && \
docker buildx build --platform linux/amd64,linux/arm64 --push -t lskjs/node:21.6.0-alpine dockerfiles/lskjs_node_21.6.0-alpine && \
docker buildx build --platform linux/amd64,linux/arm64 --push -t lskjs/node:21.6.0-alpine-gyp dockerfiles/lskjs_node_21.6.0-alpine-gyp && \
docker buildx build --platform linux/amd64,linux/arm64 --push -t lskjs/node:21.6.0-gyp dockerfiles/lskjs_node_21.6.0-gyp && \
docker buildx build --platform linux/amd64,linux/arm64 --push -t lskjs/node:21.6.0-playwright dockerfiles/lskjs_node_21.6.0-playwright && \
docker buildx build --platform linux/amd64,linux/arm64 --push -t lskjs/node:22.6.0 dockerfiles/lskjs_node_22.6.0 && \
docker buildx build --platform linux/amd64,linux/arm64 --push -t lskjs/node:22.6.0-alpine dockerfiles/lskjs_node_22.6.0-alpine && \
docker buildx build --platform linux/amd64,linux/arm64 --push -t lskjs/node:22.6.0-alpine-gyp dockerfiles/lskjs_node_22.6.0-alpine-gyp && \
docker buildx build --platform linux/amd64,linux/arm64 --push -t lskjs/node:22.6.0-gyp dockerfiles/lskjs_node_22.6.0-gyp && \
docker buildx build --platform linux/amd64,linux/arm64 --push -t lskjs/node:22.6.0-playwright dockerfiles/lskjs_node_22.6.0-playwright && \
docker buildx build --platform linux/amd64,linux/arm64 --push -t lskjs/node:latest dockerfiles/lskjs_node_latest && \
docker buildx build --platform linux/amd64,linux/arm64 --push -t lskjs/node:latest-alpine dockerfiles/lskjs_node_latest-alpine && \
docker buildx build --platform linux/amd64,linux/arm64 --push -t lskjs/node:latest-playwright dockerfiles/lskjs_node_latest-playwright && \
docker buildx build --platform linux/amd64,linux/arm64 --push -t lskjs/node:latest-puppeteer dockerfiles/lskjs_node_latest-puppeteer && \
docker buildx build --platform linux/amd64,linux/arm64 --push -t lskjs/rsync:3.16.0 dockerfiles/lskjs_rsync_3.16.0 && \
docker buildx build --platform linux/amd64,linux/arm64 --push -t lskjs/rsync:3.20.0 dockerfiles/lskjs_rsync_3.20.0 && \
docker buildx build --platform linux/amd64,linux/arm64 --push -t lskjs/rsync:latest dockerfiles/lskjs_rsync_latest && \
echo FINISH